/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pe.vista;

import com.pe.extras.Mensajes;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author JUAN
 */
public class FrmDialogFiltroPaquete extends javax.swing.JDialog {

    /**
     * Creates new form FrmDialogFiltroPaquete
     */
    String idEmpresa = null;
    String Empresa = null;
    String Servicio = null;

    public FrmDialogFiltroPaquete(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/image/ipartner.png")).getImage());
        Mensajes.centerComponent(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEmpresa = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblDesde = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jdateDesde = new com.toedter.calendar.JDateChooser();
        lblHasta = new javax.swing.JLabel();
        jdateHasta = new com.toedter.calendar.JDateChooser();
        btnBuscar = new javax.swing.JButton();
        lblDesde1 = new javax.swing.JLabel();
        cboServicios = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        setForeground(java.awt.Color.darkGray);
        setUndecorated(true);

        lblEmpresa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 3, true));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Organización :");

        lblDesde.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDesde.setText("Desde :");

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 0, 0));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jdateDesde.setDateFormatString("yyyy-MM-dd");
        jdateDesde.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        lblHasta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHasta.setText("Hasta :");

        jdateHasta.setDateFormatString("yyyy-MM-dd");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblDesde1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDesde1.setText("Servicio :");

        cboServicios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Servicio -", "Reporte de Riesgos", "Referencias Laborales", "Verificacion Domiciliaria", "Verificacion de Proveedor", "Verificaciones Academicas", "Certificado de Trabajo" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblDesde1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancelar)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDesde)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jdateDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(lblHasta)
                                .addGap(18, 18, 18)
                                .addComponent(jdateHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(404, 404, 404))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDesde1)
                    .addComponent(cboServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdateDesde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDesde)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHasta)
                            .addComponent(btnBuscar))
                        .addComponent(jdateHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(btnCancelar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEmpresa))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        ValidarServicio();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void ValidarServicio() {
        if (cboServicios.getSelectedIndex() == 0) {
            Mensajes.msjMuestra("Seleccione un Servicio");
        } else if (cboServicios.getSelectedIndex() == 1) {
            Servicio = "RR";
            Funcion_Busqueda();
        } else if (cboServicios.getSelectedIndex() == 2) {
            Servicio = "RL";
            Funcion_Busqueda();
        } else if (cboServicios.getSelectedIndex() == 3) {
            Servicio = "VD";
        } else if (cboServicios.getSelectedIndex() == 4) {
            Servicio = "VP";
        } else if (cboServicios.getSelectedIndex() == 5) {
            Servicio = "VA";
        } else if (cboServicios.getSelectedIndex() == 6) {
            Servicio = "CT";
        }
    }

    private void Funcion_Busqueda() {
        Date fechaDesde = jdateDesde.getDate();
        Date fechaHasta = jdateHasta.getDate();
        String banco_ripley = "431";

        if (fechaDesde == null || fechaHasta == null) {
            Mensajes.msjError("Complete las Fechas correctamente");
        } else if (fechaDesde.before(fechaHasta) || fechaDesde.equals(fechaHasta)) {

            SimpleDateFormat formatoInicio = new SimpleDateFormat("yyyy-MM-dd 00:00:00");
            SimpleDateFormat formatoFinal = new SimpleDateFormat("yyyy-MM-dd 23:59:59");
            String Desde = formatoInicio.format(fechaDesde);
            String Hasta = formatoFinal.format(fechaHasta);
            String servicio = Servicio;
            System.out.println(Desde);
            System.out.println(Hasta);

            JFrame f = (JFrame) JOptionPane.getFrameForComponent(this);
            FrmDialogDetallePaquete detalle = new FrmDialogDetallePaquete(f, true);

            System.out.println(idEmpresa + "mando el id");
            detalle.RecibeDatosSinPaquete(idEmpresa, Empresa, Desde, Hasta, servicio);
            detalle.lblaFavor.setVisible(false);
            detalle.txtReportesAFavor.setVisible(false);
                detalle.show();
            this.dispose();
        } else {
            Mensajes.msjError("El parametro de fecha no es correcto");
        }
    }

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    public void RecibeID(String id, String empresa) {

        System.out.println(id + "recibo el id");
        idEmpresa = id;
        Empresa = empresa;
        lblEmpresa.setText(Empresa);
        System.out.println(idEmpresa + "Paso por recibeID");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDialogFiltroPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDialogFiltroPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDialogFiltroPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDialogFiltroPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmDialogFiltroPaquete dialog = new FrmDialogFiltroPaquete(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cboServicios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser jdateDesde;
    private com.toedter.calendar.JDateChooser jdateHasta;
    private javax.swing.JLabel lblDesde;
    private javax.swing.JLabel lblDesde1;
    private javax.swing.JLabel lblEmpresa;
    private javax.swing.JLabel lblHasta;
    // End of variables declaration//GEN-END:variables
}
