/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pe.vista;

import Reportes.ReportePedidos;
import com.pe.controlador.UsuarioDAO;
import com.pe.extras.Mensajes;
import com.pe.modelo.usuario;
import com.pe.util.conexion;
import java.awt.Label;
import java.beans.PropertyVetoException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author JuanCR
 */
public class FrmPrincipal extends javax.swing.JFrame {
    /**
     * Creates new form FrmPrincipal
     */
    com.pe.vista.IFrmListaUsuario ouFrmUsu;
    com.pe.vista.IFrmVistaPaquetes ouFrmVistaPaquete;
    com.pe.vista.IFrmValidarDNI ouFrmValidarDNI;
    com.pe.vista.IFrmCambiarEstadoPedido ouFrmCambiarEstadoPedido;
    Reportes.ReportePedidos ouFrmReportesPedidos;
    
    public FrmPrincipal() {
        initComponents();
        setIconImage (new ImageIcon(getClass().getResource("/image/ipartner.png")).getImage());
        lblIdUsuario.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        miEscritorio = new javax.swing.JDesktopPane();
        lblIdUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblNombre_usuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(516, 330));

        miEscritorio.setPreferredSize(new java.awt.Dimension(516, 309));

        lblIdUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblIdUsuario.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bienvenido :");

        lblNombre_usuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNombre_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre_usuario.setText("Bienvenido :");

        miEscritorio.setLayer(lblIdUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        miEscritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        miEscritorio.setLayer(lblNombre_usuario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout miEscritorioLayout = new javax.swing.GroupLayout(miEscritorio);
        miEscritorio.setLayout(miEscritorioLayout);
        miEscritorioLayout.setHorizontalGroup(
            miEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(miEscritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(miEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(miEscritorioLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNombre_usuario))
                    .addComponent(lblIdUsuario))
                .addContainerGap(398, Short.MAX_VALUE))
        );
        miEscritorioLayout.setVerticalGroup(
            miEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, miEscritorioLayout.createSequentialGroup()
                .addContainerGap(308, Short.MAX_VALUE)
                .addComponent(lblIdUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(miEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblNombre_usuario))
                .addGap(7, 7, 7))
        );

        lblIdUsuario.getAccessibleContext().setAccessibleDescription("");

        jMenu1.setText("Inicio");

        jMenuItem1.setText("Cerrar Sesión");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Usuario");

        jMenuItem2.setText("Usuario");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Paquetes");

        jMenuItem3.setText("Info Paquetes");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Validar");

        jMenuItem4.setText("RENIEC");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuItem5.setText("ESTADO PEDIDOS");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Reportes");

        jMenuItem6.setText("ESTADO DE PEDIDOS");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(miEscritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(miEscritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if(conexion.Conexion()==null){
             Mensajes.msjMuestra("Error de Conexion");
        }else{
           Mensajes.msjconfirmacion();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

     public boolean estacerrado(Object objetos){
        JInternalFrame[] finterno=miEscritorio.getAllFrames();
        boolean cerrado=true;
        int i=0;
        while(i<finterno.length && cerrado){
            if(finterno[i]==objetos){
                cerrado=false;
            }
            i++;
        }
        return cerrado;
    }
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if(estacerrado(ouFrmUsu)){
            ouFrmUsu=new IFrmListaUsuario();
            miEscritorio.add(ouFrmUsu);
            ouFrmUsu.show();
        }else{
            try {
                ouFrmUsu.setMaximum(true);
                ouFrmUsu.setMaximum(false);
                ouFrmUsu.setLocation(500, 500);
            } catch (PropertyVetoException e) {
                Mensajes.msjMuestra("Error en: "+e.getMessage());
            }
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        if(estacerrado(ouFrmVistaPaquete)){
            ouFrmVistaPaquete=new IFrmVistaPaquetes();
            miEscritorio.add(ouFrmVistaPaquete);
            
            ouFrmVistaPaquete.show();
        }else{
            try {
                ouFrmVistaPaquete.setMaximum(true);
                ouFrmVistaPaquete.setMaximum(false);
                ouFrmVistaPaquete.setLocation(500, 500);
            } catch (PropertyVetoException e) {
                Mensajes.msjMuestra("Error en: "+e.getMessage());
            }
        }
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
         if(estacerrado(ouFrmValidarDNI)){
            ouFrmValidarDNI=new IFrmValidarDNI();
            miEscritorio.add(ouFrmValidarDNI);
            
            ouFrmValidarDNI.show();
        }else{
            try {
                ouFrmValidarDNI.setMaximum(true);
                ouFrmValidarDNI.setMaximum(false);
                ouFrmValidarDNI.setLocation(500, 500);
            } catch (PropertyVetoException e) {
                Mensajes.msjMuestra("Error en: "+e.getMessage());
            }
        }
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
           if(estacerrado(ouFrmCambiarEstadoPedido)){
            ouFrmCambiarEstadoPedido=new IFrmCambiarEstadoPedido();
            miEscritorio.add(ouFrmCambiarEstadoPedido);
            
            ouFrmCambiarEstadoPedido.show();
        }else{
            try {
                ouFrmCambiarEstadoPedido.setMaximum(true);
                ouFrmCambiarEstadoPedido.setMaximum(false);
                ouFrmCambiarEstadoPedido.setLocation(500, 500);
            } catch (PropertyVetoException e) {
                Mensajes.msjMuestra("Error en: "+e.getMessage());
            }
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
         if(estacerrado(ouFrmReportesPedidos)){
            ouFrmReportesPedidos=new ReportePedidos();
            miEscritorio.add(ouFrmReportesPedidos);
            
            ouFrmReportesPedidos.show();
        }else{
            try {
                ouFrmReportesPedidos.setMaximum(true);
                ouFrmReportesPedidos.setMaximum(false);
                ouFrmReportesPedidos.setLocation(500, 500);
            } catch (PropertyVetoException e) {
                Mensajes.msjMuestra("Error en: "+e.getMessage());
            }
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    public void exitForm() {
        this.dispose();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new  FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    public javax.swing.JLabel lblIdUsuario;
    public javax.swing.JLabel lblNombre_usuario;
    private javax.swing.JDesktopPane miEscritorio;
    // End of variables declaration//GEN-END:variables
}
