/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pe.vista;

import com.pe.controlador.Detalle_PedidoDAO;
import com.pe.extras.Mensajes;
import com.pe.extras.MyEditor;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author JUAN
 */
public class IFrmCambiarEstadoPedido extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrmCambiarEstadoPedido
     */
    public IFrmCambiarEstadoPedido() {
        initComponents();
        Mensajes.centerComponent(this);

    }
    MyEditor myEdit = new MyEditor();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnumeroDocumento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int colIndex){
                return false;
            }
        };
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cambiar Estado de Pedido");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Ingrese datos a verificar :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Numero de Documento");

        txtnumeroDocumento.setName("txtnumeroDocumento"); // NOI18N

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        jButton1.setText("Buscar");
        jButton1.setName("btnbuscar"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtnumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addGap(0, 335, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String dni = txtnumeroDocumento.getText().toString().trim();
        myEdit.VisualizarData_porDNI(tblDatos, dni);
        FormatoDatos();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void FormatoDatos() {
        tblDatos.getColumnModel().getColumn(0).setMaxWidth(0);
        tblDatos.getColumnModel().getColumn(0).setMinWidth(0);
        tblDatos.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        tblDatos.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        tblDatos.getColumnModel().getColumn(1).setMaxWidth(0);
        tblDatos.getColumnModel().getColumn(1).setMinWidth(0);
        tblDatos.getTableHeader().getColumnModel().getColumn(1).setMaxWidth(0);
        tblDatos.getTableHeader().getColumnModel().getColumn(1).setMinWidth(0);
        tblDatos.getColumnModel().getColumn(2).setMaxWidth(0);
        tblDatos.getColumnModel().getColumn(2).setMinWidth(0);
        tblDatos.getTableHeader().getColumnModel().getColumn(2).setMaxWidth(0);
        tblDatos.getTableHeader().getColumnModel().getColumn(2).setMinWidth(0);
        tblDatos.getColumnModel().getColumn(3).setMaxWidth(0);
        tblDatos.getColumnModel().getColumn(3).setMinWidth(0);
        tblDatos.getTableHeader().getColumnModel().getColumn(3).setMaxWidth(0);
        tblDatos.getTableHeader().getColumnModel().getColumn(3).setMinWidth(0);
        tblDatos.getColumnModel().getColumn(4).setPreferredWidth(200);
        tblDatos.getColumnModel().getColumn(5).setPreferredWidth(125);
        tblDatos.getColumnModel().getColumn(6).setPreferredWidth(100);
        tblDatos.getColumnModel().getColumn(7).setPreferredWidth(250);
        tblDatos.getColumnModel().getColumn(8).setPreferredWidth(100);
        tblDatos.getColumnModel().getColumn(9).setPreferredWidth(110);
        tblDatos.getColumnModel().getColumn(10).setPreferredWidth(250);
        tblDatos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblDatos.setSelectionBackground(Color.GRAY);
        tblDatos.setIntercellSpacing(new Dimension(1, 1));
        tblDatos.setRowMargin(1);
        tblDatos.setOpaque(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtnumeroDocumento;
    // End of variables declaration//GEN-END:variables
}
