/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pe.vista;

import com.pe.controlador.Detalle_PedidoDAO;
import com.pe.extras.Mensajes;
import com.pe.extras.MyEditor;
import com.pe.modelo.detalle_pedido;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author JUAN
 */
public class IFrmCambiarEstadoPedido extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrmCambiarEstadoPedido
     */
    String servicio;
    int clic_tabla = 0;

    public IFrmCambiarEstadoPedido() {
        initComponents();
        Mensajes.centerComponent(this);
    }
    MyEditor myEdit = new MyEditor();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnumeroDocumento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int colIndex){
                return false;
            }
        };
        jButton1 = new javax.swing.JButton();
        cboServicios = new javax.swing.JComboBox<>();
        lblDesde1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cambiar Estado de Pedido");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Ingrese datos a verificar :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Numero de Documento");

        txtnumeroDocumento.setName("txtnumeroDocumento"); // NOI18N

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDatos);

        jButton1.setText("Buscar");
        jButton1.setName("btnbuscar"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cboServicios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Servicio -", "Reporte de Riesgos", "Referencias Laborales", "Verificacion Domiciliaria", "Verificacion de Proveedor", "Verificaciones Academicas", "Certificado de Trabajo" }));

        lblDesde1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDesde1.setText("Servicio :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtnumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(lblDesde1)
                        .addGap(18, 18, 18)
                        .addComponent(cboServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(345, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDesde1)
                    .addComponent(cboServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String dni = txtnumeroDocumento.getText().toString().trim();

        if (cboServicios.getSelectedIndex() == 0) {
            Mensajes.msjMuestra("Seleccione un Servicio");
        } else if (cboServicios.getSelectedIndex() == 1) {
            servicio = "RR";
            myEdit.VisualizarData_porDNI(tblDatos, dni, servicio);
            FormatoDatos();
        } else if (cboServicios.getSelectedIndex() == 2) {
            servicio = "RL";
            myEdit.VisualizarData_porDNI(tblDatos, dni, servicio);
            FormatoDatos();
        } else if (cboServicios.getSelectedIndex() == 3) {
            servicio = "VD";
            myEdit.VisualizarData_porDNI(tblDatos, dni, servicio);
            FormatoDatos();
        } else if (cboServicios.getSelectedIndex() == 4) {
            servicio = "VP";
            myEdit.VisualizarData_porDNI_2(tblDatos, dni, servicio);
            FormatoDatos();
        } else if (cboServicios.getSelectedIndex() == 5) {
            servicio = "VA";
            myEdit.VisualizarData_porDNI(tblDatos, dni, servicio);
            FormatoDatos();
        } else if (cboServicios.getSelectedIndex() == 6) {
            servicio = "CT";
            myEdit.VisualizarData_porDNI(tblDatos, dni, servicio);
            FormatoDatos();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatosMouseClicked
        // TODO add your handling code here:
        clic_tabla = this.tblDatos.rowAtPoint(evt.getPoint());
        int filaseleccionada = tblDatos.getSelectedRow();
        int columna = tblDatos.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tblDatos.getRowHeight();
        String idDetallePedido = "" + tblDatos.getValueAt(filaseleccionada, 0);
        String idPedido = "" + tblDatos.getValueAt(filaseleccionada, 2);
        String fecha=""+tblDatos.getValueAt(filaseleccionada, 6);
        String paquete=""+tblDatos.getValueAt(filaseleccionada, 4);
        Object value = tblDatos.getValueAt(row, columna);
        if (value instanceof JButton) {
            ((JButton) value).doClick();
            JButton boton = (JButton) value;

            if (boton.getName().equals("btnactualizar")) {
                System.out.println("Click en el boton actualizar");
                Mensajes.msjconfirmacionActualizarPedido(fecha, idDetallePedido, idPedido);
            }
             if (boton.getName().equals("btneliminar")) {
                System.out.println("Click en el boton Eliminar");
                Mensajes.msjconfirmacionEliminarPedido(fecha, idDetallePedido, idPedido,paquete);
            }
        }

    }//GEN-LAST:event_tblDatosMouseClicked

    private void FormatoDatos() {
        tblDatos.getColumnModel().getColumn(0).setMaxWidth(0);
        tblDatos.getColumnModel().getColumn(0).setMinWidth(0);
        tblDatos.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        tblDatos.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        tblDatos.getColumnModel().getColumn(1).setMaxWidth(0);
        tblDatos.getColumnModel().getColumn(1).setMinWidth(0);
        tblDatos.getTableHeader().getColumnModel().getColumn(1).setMaxWidth(0);
        tblDatos.getTableHeader().getColumnModel().getColumn(1).setMinWidth(0);
        tblDatos.getColumnModel().getColumn(2).setMaxWidth(0);
        tblDatos.getColumnModel().getColumn(2).setMinWidth(0);
        tblDatos.getTableHeader().getColumnModel().getColumn(2).setMaxWidth(0);
        tblDatos.getTableHeader().getColumnModel().getColumn(2).setMinWidth(0);
        tblDatos.getColumnModel().getColumn(3).setMaxWidth(0);
        tblDatos.getColumnModel().getColumn(3).setMinWidth(0);
        tblDatos.getTableHeader().getColumnModel().getColumn(3).setMaxWidth(0);
        tblDatos.getTableHeader().getColumnModel().getColumn(3).setMinWidth(0);
        tblDatos.getColumnModel().getColumn(4).setMaxWidth(0);
        tblDatos.getColumnModel().getColumn(4).setMinWidth(0);
        tblDatos.getTableHeader().getColumnModel().getColumn(4).setMaxWidth(0);
        tblDatos.getTableHeader().getColumnModel().getColumn(4).setMinWidth(0);
        tblDatos.getColumnModel().getColumn(5).setPreferredWidth(200);
        tblDatos.getColumnModel().getColumn(6).setPreferredWidth(125);
        tblDatos.getColumnModel().getColumn(7).setPreferredWidth(100);
        tblDatos.getColumnModel().getColumn(8).setPreferredWidth(250);
        tblDatos.getColumnModel().getColumn(9).setPreferredWidth(100);
        tblDatos.getColumnModel().getColumn(10).setPreferredWidth(110);
        tblDatos.getColumnModel().getColumn(11).setPreferredWidth(250);
        tblDatos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblDatos.setSelectionBackground(Color.GRAY);
        tblDatos.setIntercellSpacing(new Dimension(1, 1));
        tblDatos.setRowMargin(1);
        tblDatos.setOpaque(false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboServicios;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDesde1;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtnumeroDocumento;
    // End of variables declaration//GEN-END:variables
}
