/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Reportes;

import com.pe.controlador.Detalle_PedidoDAO;
import com.pe.extras.Mensajes;
import com.pe.extras.export_excel;
import com.pe.vista.FrmDialogDetallePaquete;
import java.awt.Color;
import java.awt.Dimension;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author JUAN
 */
public class ReportePedidos extends javax.swing.JInternalFrame {

    String Servicio = null;

    /**
     * Creates new form ReportePedidos
     */
    public ReportePedidos() {
        initComponents();
        HabilitarBusqueda();
        Mensajes.centerComponent(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tipo = new javax.swing.ButtonGroup();
        cboServicios = new javax.swing.JComboBox<>();
        lblServicio = new javax.swing.JLabel();
        rbtnActualizados = new javax.swing.JRadioButton();
        rbtnEliminados = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lblDesde = new javax.swing.JLabel();
        jDateDesde = new com.toedter.calendar.JDateChooser();
        jDateHasta = new com.toedter.calendar.JDateChooser();
        lblHasta = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        btnGenerar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        cboServicios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Servicio -", "Reporte de Riesgos", "Referencias Laborales", "Verificacion Domiciliaria", "Verificacion de Proveedor", "Verificaciones Academicas", "Certificado de Trabajo" }));

        lblServicio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblServicio.setText("Servicio :");

        Tipo.add(rbtnActualizados);
        rbtnActualizados.setText("Actualizados");
        rbtnActualizados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnActualizadosActionPerformed(evt);
            }
        });

        Tipo.add(rbtnEliminados);
        rbtnEliminados.setText("Eliminados");
        rbtnEliminados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnEliminadosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Exportar Detalle");

        lblDesde.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDesde.setText("Desde :");

        jDateDesde.setDateFormatString("yyyy-MM-dd");

        jDateHasta.setDateFormatString("yyyy-MM-dd");

        lblHasta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHasta.setText("Hasta :");

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_excel.png"))); // NOI18N
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(rbtnActualizados)
                        .addGap(29, 29, 29)
                        .addComponent(rbtnEliminados))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblDesde)
                                .addGap(18, 18, 18)
                                .addComponent(jDateDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblHasta)
                                .addGap(18, 18, 18)
                                .addComponent(jDateHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblServicio)
                                .addGap(18, 18, 18)
                                .addComponent(cboServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnActualizados)
                    .addComponent(rbtnEliminados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServicio)
                    .addComponent(cboServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDesde)
                            .addComponent(jDateDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHasta)
                            .addComponent(jDateHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenerar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HabilitarBusqueda() {
        if (rbtnActualizados.isSelected() == true) {
            lblServicio.setVisible(true);
            cboServicios.setVisible(true);
            lblDesde.setVisible(true);
            jDateDesde.setVisible(true);
            lblHasta.setVisible(true);
            jDateHasta.setVisible(true);
            tblDatos.setVisible(true);
            btnBuscar.setVisible(true);
            btnGenerar.setVisible(false);
        } else if (rbtnEliminados.isSelected() == true) {
            lblServicio.setVisible(true);
            cboServicios.setVisible(true);
            lblDesde.setVisible(true);
            jDateDesde.setVisible(true);
            lblHasta.setVisible(true);
            jDateHasta.setVisible(true);
            tblDatos.setVisible(true);
            btnBuscar.setVisible(true);
            btnGenerar.setVisible(false);
        } else {
            lblServicio.setVisible(false);
            cboServicios.setVisible(false);
            lblDesde.setVisible(false);
            jDateDesde.setVisible(false);
            lblHasta.setVisible(false);
            jDateHasta.setVisible(false);
            tblDatos.setVisible(false);
            btnBuscar.setVisible(false);
            btnGenerar.setVisible(false);
        }
    }

    private void ValidarServicio() {
        if (cboServicios.getSelectedIndex() == 0) {
            Mensajes.msjMuestra("Seleccione un Servicio");
        } else if (cboServicios.getSelectedIndex() == 1) {
            Servicio = "RR";
            Funcion_Busqueda();
        } else if (cboServicios.getSelectedIndex() == 2) {
            Servicio = "RL";
            Funcion_Busqueda();
        } else if (cboServicios.getSelectedIndex() == 3) {
            Servicio = "VD";
            Funcion_Busqueda();
        } else if (cboServicios.getSelectedIndex() == 4) {
            Servicio = "VP";
            Funcion_Busqueda();
        } else if (cboServicios.getSelectedIndex() == 5) {
            Servicio = "VA";
            Funcion_Busqueda();
        } else if (cboServicios.getSelectedIndex() == 6) {
            Servicio = "CT";
            Funcion_Busqueda();
        }
    }

    private void Funcion_Busqueda() {
        Date fechaDesde = jDateDesde.getDate();
        Date fechaHasta = jDateHasta.getDate();

        if (fechaDesde == null || fechaHasta == null) {
            Mensajes.msjError("Complete las Fechas correctamente");
        } else if (fechaDesde.before(fechaHasta) || fechaDesde.equals(fechaHasta)) {

            SimpleDateFormat formatoInicio = new SimpleDateFormat("yyyy-MM-dd 00:00:00");
            SimpleDateFormat formatoFinal = new SimpleDateFormat("yyyy-MM-dd 23:59:59");
            String Desde = formatoInicio.format(fechaDesde);
            String Hasta = formatoFinal.format(fechaHasta);
            String servicio = Servicio;

            if (rbtnActualizados.isSelected() == true) {
                if (servicio.equals("VP")) {
                    System.out.println("Entro a proveedor ACTUALIZADOS");
                    tblDatos.setModel(DbUtils.resultSetToTableModel(Detalle_PedidoDAO.ReportesActualizados_2(servicio, Desde, Hasta)));
                    ValidarDatosenTabla();
                } else {
                    tblDatos.setModel(DbUtils.resultSetToTableModel(Detalle_PedidoDAO.ReportesActualizados(servicio, Desde, Hasta)));
                    ValidarDatosenTabla();
                }
            } else if (rbtnEliminados.isSelected() == true) {
                if (servicio.equals("VP")) {
                    System.out.println("Entro a proveedor eLIMINADOS");
                    tblDatos.setModel(DbUtils.resultSetToTableModel(Detalle_PedidoDAO.ReportesEliminados_2(servicio, Desde, Hasta)));
                    ValidarDatosenTabla();
                } else {
                    tblDatos.setModel(DbUtils.resultSetToTableModel(Detalle_PedidoDAO.ReportesEliminados(servicio, Desde, Hasta)));
                    ValidarDatosenTabla();
                }
            }

        } else {
            Mensajes.msjError("El parametro de fecha no es correcto");
        }
    }
    private void rbtnActualizadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnActualizadosActionPerformed
        // TODO add your handling code here:
        HabilitarBusqueda();
    }//GEN-LAST:event_rbtnActualizadosActionPerformed

    private void rbtnEliminadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnEliminadosActionPerformed
        // TODO add your handling code here:
        HabilitarBusqueda();
    }//GEN-LAST:event_rbtnEliminadosActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        ValidarServicio();
        FormatoDatos();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // TODO add your handling code here:
        JFileChooser dialog = new JFileChooser();
        int opcion = dialog.showSaveDialog(ReportePedidos.this);
        String detalle="";

        if (opcion == JFileChooser.APPROVE_OPTION) {

            File dir = dialog.getSelectedFile();

            try {
                List<JTable> tb = new ArrayList<JTable>();
                tb.add(tblDatos);
                //-------------------
                if(rbtnActualizados.isSelected()==true){
                    detalle="Reportes Actualizados";
                }else if(rbtnEliminados.isSelected()==true){
                    detalle="Reportes Eliminados";
                }
                export_excel excelExporter = new export_excel(tb, new File(dir.getAbsolutePath() + ".Xls"));
                if (excelExporter.export_ReportePedido(detalle)) {
                    JOptionPane.showMessageDialog(null, "TABLAS EXPORTADOS CON EXITOS!");

                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void ValidarDatosenTabla(){
        if(tblDatos.getRowCount()>0){
            btnGenerar.setVisible(true);
        }else{
            Mensajes.msjError("No hay Data a mostrar");
        }
    }
    private void FormatoDatos() {
        tblDatos.getColumnModel().getColumn(0).setPreferredWidth(200);
        tblDatos.getColumnModel().getColumn(1).setPreferredWidth(135);
        tblDatos.getColumnModel().getColumn(2).setPreferredWidth(100);
        tblDatos.getColumnModel().getColumn(3).setPreferredWidth(250);
        tblDatos.getColumnModel().getColumn(4).setPreferredWidth(260);
        tblDatos.getColumnModel().getColumn(5).setPreferredWidth(220);
        tblDatos.getColumnModel().getColumn(6).setPreferredWidth(260);
        tblDatos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblDatos.setSelectionBackground(Color.GRAY);
        tblDatos.setIntercellSpacing(new Dimension(1, 1));
        tblDatos.setRowMargin(1);
        tblDatos.setOpaque(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Tipo;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JComboBox<String> cboServicios;
    private com.toedter.calendar.JDateChooser jDateDesde;
    private com.toedter.calendar.JDateChooser jDateHasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblDesde;
    private javax.swing.JLabel lblHasta;
    private javax.swing.JLabel lblServicio;
    private javax.swing.JRadioButton rbtnActualizados;
    private javax.swing.JRadioButton rbtnEliminados;
    private javax.swing.JTable tblDatos;
    // End of variables declaration//GEN-END:variables
}
